# -*- coding: utf-8 -*-
"""Единая конфигурация CareerAI."""

from config.model_config import (
    DUBNA_DIRECTION_KEYS,
    DUBNA_CODES,
    EXPANDED_FEATURES,
    DIRECTION_KEY_SKILLS,
    DIRECTION_KEY_SKILLS_TEXT,
    DIRECTION_DESCRIPTIONS,
    DIRECTION_SKILLS_MAP,
    SKILL_NAMES,
    FEATURE_LABELS,
    DEFAULT_FEATURE_VALUES,
    UNIVERSITY_NAME,
    UNIVERSITY_URL,
    ABITUR_URL,
    DIRECTIONS_SOURCE,
    MODEL_DIR,
)

__all__ = [
    "DUBNA_DIRECTION_KEYS",
    "DUBNA_CODES",
    "EXPANDED_FEATURES",
    "DIRECTION_KEY_SKILLS",
    "DIRECTION_KEY_SKILLS_TEXT",
    "DIRECTION_DESCRIPTIONS",
    "DIRECTION_SKILLS_MAP",
    "SKILL_NAMES",
    "FEATURE_LABELS",
    "DEFAULT_FEATURE_VALUES",
    "UNIVERSITY_NAME",
    "UNIVERSITY_URL",
    "ABITUR_URL",
    "DIRECTIONS_SOURCE",
    "MODEL_DIR",
]
